@baseUrl=http://localhost:3000/api/v1

### Get users
GET {{baseUrl}}/users

### Create user
POST {{baseUrl}}/users 
Content-Type: application/json

{
  "username": "test@test.com",
  "password": "qwerQWER1234!@#$",
  "passwordConfirm": "qwerQWER1234!@#$",
  "displayName": "myName"
}

### Admin Login
# @name adminLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "username": "admin@admin.com",
  "password": "qwerQWER1234!@#$"
}

### 
@adminToken = {{adminLogin.response.body.$.token}}

### User Login
# @name userLogin
POST {{baseUrl}}/auth/login
Content-type: application/json

{
  "username": "user1@user.com",
  "password": "qwerQWER1234!@#$"
}

###
@userToken = {{userLogin.response.body.$.token}}

### Get all posts
GET {{baseUrl}}/posts

### Create post
POST {{baseUrl}}/posts
Authorization: {{adminToken}}
Content-Type: application/json

{
  "title": "First Post",
  "content": "Hello, Blog!",
  "published": true
}

### Update post
PUT {{baseUrl}}/posts/1
Authorization: {{adminToken}}
Content-Type: application/json

{
  "title": "Updated First Post",
  "content": "Hello again, Blog!",
  "published": true
}

### Delete post
DELETE {{baseUrl}}/posts/1
Authorization: {{adminToken}}